test_runner: !test_runner
  test_functions:
    - average_cbr_test

  tested_configurations: 
    - veins
    - inet

  results_dir: results
  sim_time_limit: 90

scenario: !scenario
  cbr: greater
  cbr_threshold: 0.0
