# CMake generated Testfile for 
# Source directory: /home/ilya-cavise/artery/scenarios/gemv2
# Build directory: /home/ilya-cavise/artery/scenarios/scenarios/gemv2
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(gemv2-LOS "/home/ilya-cavise/omnetpp/bin/opp_run_dbg" "-n" "/home/ilya-cavise/artery/src/artery:/home/ilya-cavise/artery/src/traci:/home/ilya-cavise/artery/extern/veins/examples/veins:/home/ilya-cavise/artery/extern/veins/src/veins:/home/ilya-cavise/artery/extern/inet/src:/home/ilya-cavise/artery/extern/inet/examples:/home/ilya-cavise/artery/extern/inet/tutorials:/home/ilya-cavise/artery/extern/inet/showcases" "-l" "/home/ilya-cavise/artery/scenarios/src/artery/envmod/libartery_envmod.so" "-l" "/home/ilya-cavise/artery/scenarios/src/artery/storyboard/libartery_storyboard.so" "-l" "/home/ilya-cavise/artery/scenarios/extern/libINET.so" "-l" "/home/ilya-cavise/artery/scenarios/extern/libveins.so" "-l" "/home/ilya-cavise/artery/scenarios/src/traci/libtraci.so" "-l" "/home/ilya-cavise/artery/scenarios/src/artery/libartery_core.so" "omnetpp.ini" "-uCmdenv" "-cLOS_mediumAntennas" "--sim-time-limit=10s")
set_tests_properties(gemv2-LOS PROPERTIES  WORKING_DIRECTORY "/home/ilya-cavise/artery/scenarios/gemv2" _BACKTRACE_TRIPLES "/home/ilya-cavise/artery/cmake/AddOppRun.cmake;170;add_test;/home/ilya-cavise/artery/scenarios/gemv2/CMakeLists.txt;3;add_opp_test;/home/ilya-cavise/artery/scenarios/gemv2/CMakeLists.txt;0;")
add_test(gemv2-NLOSv "/home/ilya-cavise/omnetpp/bin/opp_run_dbg" "-n" "/home/ilya-cavise/artery/src/artery:/home/ilya-cavise/artery/src/traci:/home/ilya-cavise/artery/extern/veins/examples/veins:/home/ilya-cavise/artery/extern/veins/src/veins:/home/ilya-cavise/artery/extern/inet/src:/home/ilya-cavise/artery/extern/inet/examples:/home/ilya-cavise/artery/extern/inet/tutorials:/home/ilya-cavise/artery/extern/inet/showcases" "-l" "/home/ilya-cavise/artery/scenarios/src/artery/envmod/libartery_envmod.so" "-l" "/home/ilya-cavise/artery/scenarios/src/artery/storyboard/libartery_storyboard.so" "-l" "/home/ilya-cavise/artery/scenarios/extern/libINET.so" "-l" "/home/ilya-cavise/artery/scenarios/extern/libveins.so" "-l" "/home/ilya-cavise/artery/scenarios/src/traci/libtraci.so" "-l" "/home/ilya-cavise/artery/scenarios/src/artery/libartery_core.so" "omnetpp.ini" "-uCmdenv" "-cNLOSv" "--sim-time-limit=10s")
set_tests_properties(gemv2-NLOSv PROPERTIES  WORKING_DIRECTORY "/home/ilya-cavise/artery/scenarios/gemv2" _BACKTRACE_TRIPLES "/home/ilya-cavise/artery/cmake/AddOppRun.cmake;170;add_test;/home/ilya-cavise/artery/scenarios/gemv2/CMakeLists.txt;4;add_opp_test;/home/ilya-cavise/artery/scenarios/gemv2/CMakeLists.txt;0;")
add_test(gemv2-NLOSbLogDist "/home/ilya-cavise/omnetpp/bin/opp_run_dbg" "-n" "/home/ilya-cavise/artery/src/artery:/home/ilya-cavise/artery/src/traci:/home/ilya-cavise/artery/extern/veins/examples/veins:/home/ilya-cavise/artery/extern/veins/src/veins:/home/ilya-cavise/artery/extern/inet/src:/home/ilya-cavise/artery/extern/inet/examples:/home/ilya-cavise/artery/extern/inet/tutorials:/home/ilya-cavise/artery/extern/inet/showcases" "-l" "/home/ilya-cavise/artery/scenarios/src/artery/envmod/libartery_envmod.so" "-l" "/home/ilya-cavise/artery/scenarios/src/artery/storyboard/libartery_storyboard.so" "-l" "/home/ilya-cavise/artery/scenarios/extern/libINET.so" "-l" "/home/ilya-cavise/artery/scenarios/extern/libveins.so" "-l" "/home/ilya-cavise/artery/scenarios/src/traci/libtraci.so" "-l" "/home/ilya-cavise/artery/scenarios/src/artery/libartery_core.so" "omnetpp.ini" "-uCmdenv" "-cNLOSb1" "--sim-time-limit=10s")
set_tests_properties(gemv2-NLOSbLogDist PROPERTIES  WORKING_DIRECTORY "/home/ilya-cavise/artery/scenarios/gemv2" _BACKTRACE_TRIPLES "/home/ilya-cavise/artery/cmake/AddOppRun.cmake;170;add_test;/home/ilya-cavise/artery/scenarios/gemv2/CMakeLists.txt;5;add_opp_test;/home/ilya-cavise/artery/scenarios/gemv2/CMakeLists.txt;0;")
add_test(gemv2-NLOSbDifRefl "/home/ilya-cavise/omnetpp/bin/opp_run_dbg" "-n" "/home/ilya-cavise/artery/src/artery:/home/ilya-cavise/artery/src/traci:/home/ilya-cavise/artery/extern/veins/examples/veins:/home/ilya-cavise/artery/extern/veins/src/veins:/home/ilya-cavise/artery/extern/inet/src:/home/ilya-cavise/artery/extern/inet/examples:/home/ilya-cavise/artery/extern/inet/tutorials:/home/ilya-cavise/artery/extern/inet/showcases" "-l" "/home/ilya-cavise/artery/scenarios/src/artery/envmod/libartery_envmod.so" "-l" "/home/ilya-cavise/artery/scenarios/src/artery/storyboard/libartery_storyboard.so" "-l" "/home/ilya-cavise/artery/scenarios/extern/libINET.so" "-l" "/home/ilya-cavise/artery/scenarios/extern/libveins.so" "-l" "/home/ilya-cavise/artery/scenarios/src/traci/libtraci.so" "-l" "/home/ilya-cavise/artery/scenarios/src/artery/libartery_core.so" "omnetpp.ini" "-uCmdenv" "-cNLOSb1_diffractionReflection" "--sim-time-limit=10s")
set_tests_properties(gemv2-NLOSbDifRefl PROPERTIES  WORKING_DIRECTORY "/home/ilya-cavise/artery/scenarios/gemv2" _BACKTRACE_TRIPLES "/home/ilya-cavise/artery/cmake/AddOppRun.cmake;170;add_test;/home/ilya-cavise/artery/scenarios/gemv2/CMakeLists.txt;6;add_opp_test;/home/ilya-cavise/artery/scenarios/gemv2/CMakeLists.txt;0;")
add_test(gemv2-NLOSbSmallScale "/home/ilya-cavise/omnetpp/bin/opp_run_dbg" "-n" "/home/ilya-cavise/artery/src/artery:/home/ilya-cavise/artery/src/traci:/home/ilya-cavise/artery/extern/veins/examples/veins:/home/ilya-cavise/artery/extern/veins/src/veins:/home/ilya-cavise/artery/extern/inet/src:/home/ilya-cavise/artery/extern/inet/examples:/home/ilya-cavise/artery/extern/inet/tutorials:/home/ilya-cavise/artery/extern/inet/showcases" "-l" "/home/ilya-cavise/artery/scenarios/src/artery/envmod/libartery_envmod.so" "-l" "/home/ilya-cavise/artery/scenarios/src/artery/storyboard/libartery_storyboard.so" "-l" "/home/ilya-cavise/artery/scenarios/extern/libINET.so" "-l" "/home/ilya-cavise/artery/scenarios/extern/libveins.so" "-l" "/home/ilya-cavise/artery/scenarios/src/traci/libtraci.so" "-l" "/home/ilya-cavise/artery/scenarios/src/artery/libartery_core.so" "omnetpp.ini" "-uCmdenv" "-cNLOSb1_smallScaleVariations" "--sim-time-limit=10s")
set_tests_properties(gemv2-NLOSbSmallScale PROPERTIES  WORKING_DIRECTORY "/home/ilya-cavise/artery/scenarios/gemv2" _BACKTRACE_TRIPLES "/home/ilya-cavise/artery/cmake/AddOppRun.cmake;170;add_test;/home/ilya-cavise/artery/scenarios/gemv2/CMakeLists.txt;7;add_opp_test;/home/ilya-cavise/artery/scenarios/gemv2/CMakeLists.txt;0;")
