# CMake generated Testfile for 
# Source directory: /home/ilya-cavise/artery/scenarios/storyboard
# Build directory: /home/ilya-cavise/artery/scenarios/scenarios/storyboard
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(storyboard-inet "/home/ilya-cavise/omnetpp/bin/opp_run_dbg" "-n" "/home/ilya-cavise/artery/src/artery:/home/ilya-cavise/artery/src/traci:/home/ilya-cavise/artery/extern/veins/examples/veins:/home/ilya-cavise/artery/extern/veins/src/veins:/home/ilya-cavise/artery/extern/inet/src:/home/ilya-cavise/artery/extern/inet/examples:/home/ilya-cavise/artery/extern/inet/tutorials:/home/ilya-cavise/artery/extern/inet/showcases" "-l" "/home/ilya-cavise/artery/scenarios/src/artery/envmod/libartery_envmod.so" "-l" "/home/ilya-cavise/artery/scenarios/scenarios/highway-police/libartery_police.so" "-l" "/home/ilya-cavise/artery/scenarios/src/artery/envmod/libartery_envmod.so" "-l" "/home/ilya-cavise/artery/scenarios/src/artery/storyboard/libartery_storyboard.so" "-l" "/home/ilya-cavise/artery/scenarios/extern/libINET.so" "-l" "/home/ilya-cavise/artery/scenarios/extern/libveins.so" "-l" "/home/ilya-cavise/artery/scenarios/src/traci/libtraci.so" "-l" "/home/ilya-cavise/artery/scenarios/src/artery/libartery_core.so" "omnetpp.ini" "-uCmdenv" "--sim-time-limit=60s")
set_tests_properties(storyboard-inet PROPERTIES  WORKING_DIRECTORY "/home/ilya-cavise/artery/scenarios/storyboard" _BACKTRACE_TRIPLES "/home/ilya-cavise/artery/cmake/AddOppRun.cmake;170;add_test;/home/ilya-cavise/artery/scenarios/storyboard/CMakeLists.txt;2;add_opp_test;/home/ilya-cavise/artery/scenarios/storyboard/CMakeLists.txt;0;")
add_test(storyboard-veins "/home/ilya-cavise/omnetpp/bin/opp_run_dbg" "-n" "/home/ilya-cavise/artery/src/artery:/home/ilya-cavise/artery/src/traci:/home/ilya-cavise/artery/extern/veins/examples/veins:/home/ilya-cavise/artery/extern/veins/src/veins:/home/ilya-cavise/artery/extern/inet/src:/home/ilya-cavise/artery/extern/inet/examples:/home/ilya-cavise/artery/extern/inet/tutorials:/home/ilya-cavise/artery/extern/inet/showcases" "-l" "/home/ilya-cavise/artery/scenarios/src/artery/envmod/libartery_envmod.so" "-l" "/home/ilya-cavise/artery/scenarios/scenarios/highway-police/libartery_police.so" "-l" "/home/ilya-cavise/artery/scenarios/src/artery/envmod/libartery_envmod.so" "-l" "/home/ilya-cavise/artery/scenarios/src/artery/storyboard/libartery_storyboard.so" "-l" "/home/ilya-cavise/artery/scenarios/extern/libINET.so" "-l" "/home/ilya-cavise/artery/scenarios/extern/libveins.so" "-l" "/home/ilya-cavise/artery/scenarios/src/traci/libtraci.so" "-l" "/home/ilya-cavise/artery/scenarios/src/artery/libartery_core.so" "omnetpp.ini" "-uCmdenv" "-cveins" "--sim-time-limit=60s")
set_tests_properties(storyboard-veins PROPERTIES  WORKING_DIRECTORY "/home/ilya-cavise/artery/scenarios/storyboard" _BACKTRACE_TRIPLES "/home/ilya-cavise/artery/cmake/AddOppRun.cmake;170;add_test;/home/ilya-cavise/artery/scenarios/storyboard/CMakeLists.txt;3;add_opp_test;/home/ilya-cavise/artery/scenarios/storyboard/CMakeLists.txt;0;")
add_test(storyboard-repeat "/home/ilya-cavise/omnetpp/bin/opp_run_dbg" "-n" "/home/ilya-cavise/artery/src/artery:/home/ilya-cavise/artery/src/traci:/home/ilya-cavise/artery/extern/veins/examples/veins:/home/ilya-cavise/artery/extern/veins/src/veins:/home/ilya-cavise/artery/extern/inet/src:/home/ilya-cavise/artery/extern/inet/examples:/home/ilya-cavise/artery/extern/inet/tutorials:/home/ilya-cavise/artery/extern/inet/showcases" "-l" "/home/ilya-cavise/artery/scenarios/src/artery/envmod/libartery_envmod.so" "-l" "/home/ilya-cavise/artery/scenarios/scenarios/highway-police/libartery_police.so" "-l" "/home/ilya-cavise/artery/scenarios/src/artery/envmod/libartery_envmod.so" "-l" "/home/ilya-cavise/artery/scenarios/src/artery/storyboard/libartery_storyboard.so" "-l" "/home/ilya-cavise/artery/scenarios/extern/libINET.so" "-l" "/home/ilya-cavise/artery/scenarios/extern/libveins.so" "-l" "/home/ilya-cavise/artery/scenarios/src/traci/libtraci.so" "-l" "/home/ilya-cavise/artery/scenarios/src/artery/libartery_core.so" "omnetpp.ini" "-uCmdenv" "-crepeat")
set_tests_properties(storyboard-repeat PROPERTIES  WORKING_DIRECTORY "/home/ilya-cavise/artery/scenarios/storyboard" _BACKTRACE_TRIPLES "/home/ilya-cavise/artery/cmake/AddOppRun.cmake;170;add_test;/home/ilya-cavise/artery/scenarios/storyboard/CMakeLists.txt;4;add_opp_test;/home/ilya-cavise/artery/scenarios/storyboard/CMakeLists.txt;0;")
