[General]
network = artery.inet.World

# Works nicely with backwards. Just make sure that
# stack unwinding does not crash the kernel :)
debug-on-errors = true

cmdenv-express-mode = false
cmdenv-event-banners = false
cmdenv-autoflush = true

cmdenv-output-file = ".cmdenv-log"
**.cmdenv-log-level = debug

**.scalar-recording = true
**.vector-recording = true
outputscalarmanager-class = "omnetpp::envir::SqliteOutputScalarManager"
outputvectormanager-class = "omnetpp::envir::SqliteOutputVectorManager"
output-scalar-file = ${resultdir}/${configname}-${runnumber}-scalars.sqlite
output-vector-file = ${resultdir}/${configname}-${runnumber}-vectors.sqlite

*.traci.launcher.sumo = "sumo"
*.traci.launcher.typename = "PosixLauncher"
*.traci.launcher.sumocfg = "limassol.sumocfg"

# Turn on physical env for sim and configure it for Sionna.
*.withPhysicalEnvironment = true
*.physicalEnvironment.typename = "cavise.sionna.environment.SionnaPhysicalEnvironment"

# Radio is overridden to reflect tx and rx devices in scene and provide gain
# calculations. Currently, PathLoss from INET lacks rx parameter in computation,
# analog model is also overridden to support custom signal gain computation.
*.radioMedium.analogModelType = "cavise.sionna.environment.SionnaScalarAnalogModel"
*.radioMedium.pathLossType = "cavise.sionna.environment.SionnaPathLoss"
*.radioMedium.pathLoss.solverConfig = xmldoc("path-solver.xml")

*.node[*].wlan[*].typename = "VanetNic"
*.node[*].wlan[*].radio.channelNumber = 180
*.node[*].wlan[*].radio.carrierFrequency = 5.9 GHz
*.node[*].wlan[*].radio.transmitter.power = 200 mW

*.node[*].middleware.updateInterval = 0.1s
*.node[*].middleware.datetime = "2013-06-01 12:35:00"
*.node[*].middleware.services = xmldoc("services.xml")

# Mobility and dynamic entities stuff.
# Mobility provides native Sionna coordinates to consumers that need them antenna, transmitter
# and receiver devices just create/configure the scene.
*.node[*].mobility.typename = "cavise.sionna.environment.config.dynamic.SionnaVehicleActor"
*.node[*].wlan[*].radio.antennaType = "cavise.sionna.environment.radio.SionnaPlanarAntennaArray"
*.node[*].wlan[*].radio.transmitterType = "cavise.sionna.environment.radio.SionnaVanetTransmitter"
*.node[*].wlan[*].radio.receiverType = "cavise.sionna.environment.radio.SionnaVanetReceiver"

# Used to set global antennas for tx/rx devices.
*.node[0].wlan[*].radio.antenna.sceneArrayRole = "tx"
*.node[1].wlan[*].radio.antenna.sceneArrayRole = "rx"

# Static scene config. You may optimize scene by merging shapes, reducing total objects' size.
*.physicalEnvironment.sceneConfigProvider.scenePath = "limassol-scene.xml"
*.physicalEnvironment.sceneConfigProvider.mergeMeshes = false
*.physicalEnvironment.sceneConfigProvider.mergeEquivalent = false

# Some unholy settings to transform sionna coordinates into SUMO coords and in reverse.
# Currently, you do that by placing two points in places you think are identical and then
# computing this via special script. Might be better ways to do this though.
*.physicalEnvironment.remapMatrix = xmldoc("transforms.xml", "/transforms/sumoToSionnaRemap")
*.physicalEnvironment.rotationMatrix = xmldoc("transforms.xml", "/transforms/sumoToSionnaRotation")
*.physicalEnvironment.translationVector = xmldoc("transforms.xml", "/transforms/sumoToSionnaTranslation")

# Built-in visualizer supports defining cameras and choosing colors for rays.
*.physicalEnvironment.sceneVisualizer.cameraConfig = xmldoc("cameras.xml")
*.physicalEnvironment.sceneVisualizer.interactionColorConfig = xmldoc("interaction-colors.xml")
*.physicalEnvironment.sceneVisualizer.outputDir = "results/limassol"

[Config sumo_gui]
*.traci.launcher.sumo = "sumo-gui"
