# CMake generated Testfile for 
# Source directory: /home/ilya-cavise/artery/scenarios/rsu_grid
# Build directory: /home/ilya-cavise/artery/scenarios/scenarios/rsu_grid
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(rsu_grid-omnidirectional "/home/ilya-cavise/omnetpp/bin/opp_run_dbg" "-n" "/home/ilya-cavise/artery/src/artery:/home/ilya-cavise/artery/src/traci:/home/ilya-cavise/artery/extern/veins/examples/veins:/home/ilya-cavise/artery/extern/veins/src/veins:/home/ilya-cavise/artery/extern/inet/src:/home/ilya-cavise/artery/extern/inet/examples:/home/ilya-cavise/artery/extern/inet/tutorials:/home/ilya-cavise/artery/extern/inet/showcases" "-l" "/home/ilya-cavise/artery/scenarios/src/artery/envmod/libartery_envmod.so" "-l" "/home/ilya-cavise/artery/scenarios/scenarios/highway-police/libartery_police.so" "-l" "/home/ilya-cavise/artery/scenarios/src/artery/envmod/libartery_envmod.so" "-l" "/home/ilya-cavise/artery/scenarios/src/artery/storyboard/libartery_storyboard.so" "-l" "/home/ilya-cavise/artery/scenarios/extern/libINET.so" "-l" "/home/ilya-cavise/artery/scenarios/extern/libveins.so" "-l" "/home/ilya-cavise/artery/scenarios/src/traci/libtraci.so" "-l" "/home/ilya-cavise/artery/scenarios/src/artery/libartery_core.so" "omnetpp.ini" "-uCmdenv" "-comnidirectional_test")
set_tests_properties(rsu_grid-omnidirectional PROPERTIES  WORKING_DIRECTORY "/home/ilya-cavise/artery/scenarios/rsu_grid" _BACKTRACE_TRIPLES "/home/ilya-cavise/artery/cmake/AddOppRun.cmake;170;add_test;/home/ilya-cavise/artery/scenarios/rsu_grid/CMakeLists.txt;2;add_opp_test;/home/ilya-cavise/artery/scenarios/rsu_grid/CMakeLists.txt;0;")
add_test(rsu_grid-directional "/home/ilya-cavise/omnetpp/bin/opp_run_dbg" "-n" "/home/ilya-cavise/artery/src/artery:/home/ilya-cavise/artery/src/traci:/home/ilya-cavise/artery/extern/veins/examples/veins:/home/ilya-cavise/artery/extern/veins/src/veins:/home/ilya-cavise/artery/extern/inet/src:/home/ilya-cavise/artery/extern/inet/examples:/home/ilya-cavise/artery/extern/inet/tutorials:/home/ilya-cavise/artery/extern/inet/showcases" "-l" "/home/ilya-cavise/artery/scenarios/src/artery/envmod/libartery_envmod.so" "-l" "/home/ilya-cavise/artery/scenarios/scenarios/highway-police/libartery_police.so" "-l" "/home/ilya-cavise/artery/scenarios/src/artery/envmod/libartery_envmod.so" "-l" "/home/ilya-cavise/artery/scenarios/src/artery/storyboard/libartery_storyboard.so" "-l" "/home/ilya-cavise/artery/scenarios/extern/libINET.so" "-l" "/home/ilya-cavise/artery/scenarios/extern/libveins.so" "-l" "/home/ilya-cavise/artery/scenarios/src/traci/libtraci.so" "-l" "/home/ilya-cavise/artery/scenarios/src/artery/libartery_core.so" "omnetpp.ini" "-uCmdenv" "-cdirectional_test")
set_tests_properties(rsu_grid-directional PROPERTIES  WORKING_DIRECTORY "/home/ilya-cavise/artery/scenarios/rsu_grid" _BACKTRACE_TRIPLES "/home/ilya-cavise/artery/cmake/AddOppRun.cmake;170;add_test;/home/ilya-cavise/artery/scenarios/rsu_grid/CMakeLists.txt;3;add_opp_test;/home/ilya-cavise/artery/scenarios/rsu_grid/CMakeLists.txt;0;")
add_test(rsu_grid-rsu_sensors "/home/ilya-cavise/omnetpp/bin/opp_run_dbg" "-n" "/home/ilya-cavise/artery/src/artery:/home/ilya-cavise/artery/src/traci:/home/ilya-cavise/artery/extern/veins/examples/veins:/home/ilya-cavise/artery/extern/veins/src/veins:/home/ilya-cavise/artery/extern/inet/src:/home/ilya-cavise/artery/extern/inet/examples:/home/ilya-cavise/artery/extern/inet/tutorials:/home/ilya-cavise/artery/extern/inet/showcases" "-l" "/home/ilya-cavise/artery/scenarios/src/artery/envmod/libartery_envmod.so" "-l" "/home/ilya-cavise/artery/scenarios/scenarios/highway-police/libartery_police.so" "-l" "/home/ilya-cavise/artery/scenarios/src/artery/envmod/libartery_envmod.so" "-l" "/home/ilya-cavise/artery/scenarios/src/artery/storyboard/libartery_storyboard.so" "-l" "/home/ilya-cavise/artery/scenarios/extern/libINET.so" "-l" "/home/ilya-cavise/artery/scenarios/extern/libveins.so" "-l" "/home/ilya-cavise/artery/scenarios/src/traci/libtraci.so" "-l" "/home/ilya-cavise/artery/scenarios/src/artery/libartery_core.so" "omnetpp.ini" "-uCmdenv" "-crsu_sensors_test")
set_tests_properties(rsu_grid-rsu_sensors PROPERTIES  WORKING_DIRECTORY "/home/ilya-cavise/artery/scenarios/rsu_grid" _BACKTRACE_TRIPLES "/home/ilya-cavise/artery/cmake/AddOppRun.cmake;170;add_test;/home/ilya-cavise/artery/scenarios/rsu_grid/CMakeLists.txt;4;add_opp_test;/home/ilya-cavise/artery/scenarios/rsu_grid/CMakeLists.txt;0;")
