name: Prepare GitHub containers

on:
  push:
    branches: [main]
  workflow_call:

jobs:
  build-docker-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    strategy:
      matrix:
        include:
          - name: ci-minimal
            build_artery: "false"
          - name: full-image
            build_artery: "true"

    steps:
      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/checkout@v5

      - name: Set up Docker buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push ${{ matrix.name }}
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ghcr.io/cavise/artery-gh-runner:${{ matrix.name }}
          build-args: |
            BUILD_ARTERY=${{ matrix.build_artery }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
