name: Prepare GitHub container

on:
  push:
    branches: [main]
  workflow_call:

jobs:
  build-base:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/checkout@v5
      - uses: docker/setup-buildx-action@v3
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ghcr.io/cavise/artery:base
          cache-from: type=gha
          cache-to: type=gha,mode=max

  build-cache:
    runs-on: ubuntu-latest
    needs: base
    permissions: 
      contents: read
      packages: write

    steps:
      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/checkout@v5
      - uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: .github/docker/prebuilt/Dockerfile
          push: true
          tags: ghcr.io/cavise/artery:prebuilt
          cache-from: type=gha
          cache-to: type=gha,mode=max
